# Generated by Django 6.0.3 on 2026-03-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, choices=[('black', 'Black'), ('blue', 'Blue'), ('white', 'White'), ('red', 'Red'), ('green', 'Green'), ('yellow', 'Yellow'), ('pink', 'Pink'), ('purple', 'Purple'), ('orange', 'Orange'), ('brown', 'Brown'), ('gray', 'Gray'), ('multicolor', 'Multicolor')], max_length=20, null=True, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='product',
            name='dial_shape',
            field=models.CharField(blank=True, choices=[('round', 'Round'), ('square', 'Square'), ('rectangle', 'Rectangle'), ('oval', 'Oval'), ('heart', 'Heart')], max_length=20, null=True, verbose_name='Dial Shape'),
        ),
        migrations.AddField(
            model_name='product',
            name='fabric',
            field=models.CharField(blank=True, choices=[('cotton', 'Cotton'), ('polycotton', 'Polycotton'), ('wool', 'Wool'), ('silk', 'Silk'), ('linen', 'Linen'), ('polyester', 'Polyester'), ('denim', 'Denim'), ('nylon', 'Nylon'), ('rayon', 'Rayon')], max_length=20, null=True, verbose_name='Fabric'),
        ),
    ]
