# Generated by Django 6.0.3 on 2026-03-24 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_productimage_options_alter_productimage_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Product Image', 'verbose_name_plural': 'Product Images'},
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_slug_3edc0c_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_categor_c898cc_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_gender_9ef2ce_idx',
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='dial_shape',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Dial Shape'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fabric',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Fabric'),
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('kids', 'Kids'), ('unisex', 'Unisex')], default='unisex', max_length=20, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/gallery/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product'),
        ),
    ]
